### ISSUE TITLE
Not importing

### ISSUE THREAD

**Issue by erichaus** [ivanvanderbyl/ember-uuid#2]
Hello, I just tried to install this and use it and it seems like the import isn't working? I'm on ember 1.13.11

```
import ResizeMixin from '../mixins/resize'
import config from '../config/environment'
import { v1, v4 } from 'ember-uuid'

FooPanelComponent = Ember.Component.extend ResizeMixin,
  ...
```

v1, v4 are undefined... the folder does exist in proj/node_modules/ember-uuid/

**Comment by ksamc** [comment]
Hey @erichonkanen,

You can import it by writing the following instead:

```
import { v1, v4 } from 'ember-uuid/utils/uuid-generator';
```

**Comment by ivanvanderbyl** [comment]
Thanks for reporting, I think this is a change in the way ember-cli does a few things which we never backwards tested. I'll look into it.

**Comment by erichaus** [comment]
ok great thanks
