### ISSUE TITLE
Please release 1.0.1 

### ISSUE THREAD

**Issue by psteininger** [ivanvanderbyl/ember-uuid#5]
Hi, i noticed a deprecation stemming from an old version of `ember-cli-babel` in version 1.0.0 and that it was updated last month. Could you release the update? It would help eliminate the deprecations in Ember CLI 2.18

**Comment by raido** [comment]
@ivanvanderbyl a release would be awesome :)

**Comment by jrock2004** [comment]
@ivanvanderbyl can you help us out and release `1.0.1` or are you not planning on maintaining the project any longer?

**Comment by ivanvanderbyl** [comment]
Anyone want to take it over? I'll make you an owner, I don't have time anymore.

**Comment by raido** [comment]
@ivanvanderbyl I can take it over.

**Comment by ivanvanderbyl** [comment]
@raido Done. Gave you access on NPM as well. Publish away :shipit:

**Comment by raido** [comment]
v1.0.1 released 🚀
